# Generated by Django 2.2.4 on 2019-09-06 02:59

from django.db import migrations

def create_table(apps, schema_editor):
    from ..dynamo_tables import ToDoModel
    ToDoModel.create_table(wait=True)


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20190906_0227'),
    ]

    operations = [
        migrations.RunPython(create_table),
    ]
