# Generated by Django 2.2.4 on 2019-09-06 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190906_0259'),
    ]

    operations = [
    ]
