# Generated by Django 2.2.4 on 2019-09-06 04:21
from django.db import migrations


def create_table(apps, schema_editor):
    import boto3
    dynamodb = boto3.resource(
        'dynamodb',
        region_name='ap-northeast-1',
        endpoint_url="http://dynamo:8000",
        aws_access_key_id='ACCESS_ID',
        aws_secret_access_key='ACCESS_KEY'
    )

    table = dynamodb.create_table(
        TableName='Movies',
        KeySchema=[
            {
                'AttributeName': 'year',
                'KeyType': 'HASH'  # Partition key
            },
            {
                'AttributeName': 'title',
                'KeyType': 'RANGE'  # Sort key
            }
        ],
        AttributeDefinitions=[
            {
                'AttributeName': 'year',
                'AttributeType': 'N'
            },
            {
                'AttributeName': 'title',
                'AttributeType': 'S'
            },

        ],
        ProvisionedThroughput={
            'ReadCapacityUnits': 10,
            'WriteCapacityUnits': 10
        }
    )

    print("Table status:", table.table_status)


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_table),
    ]
