# Generated by Django 2.2.4 on 2019-09-06 04:31

from django.db import migrations


def load_data(apps, schema_editor):
    import boto3
    import json
    import decimal

    dynamodb = boto3.resource(
        'dynamodb',
        region_name='ap-northeast-1',
        endpoint_url="http://dynamo:8000",
        aws_access_key_id='ACCESS_ID',
        aws_secret_access_key='ACCESS_KEY'
    )

    table = dynamodb.Table('Movies')

    with open("movie/fixtures/moviedata.json") as json_file:
        movies = json.load(json_file, parse_float=decimal.Decimal)
        for movie in movies:
            year = int(movie['year'])
            title = movie['title']
            info = movie['info']

            print("Adding movie:", year, title)

            table.put_item(
                Item={
                    'year': year,
                    'title': title,
                    'info': info,
                }
            )


class Migration(migrations.Migration):
    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data),
    ]
